# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "354297dce039f55716d885aa08c7895e"
application_url = "https://explain-treasure-inches-looked.trycloudflare.com"
embedded = true
name = "Secure Sync"
handle = "secure-sync"

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders, read_products, write_products, write_shipping, read_shipping, read_analytics, write_assigned_fulfillment_orders, read_assigned_fulfillment_orders, read_customer_events, write_checkout_branding_settings, read_checkout_branding_settings, write_custom_pixels, read_custom_pixels, write_customers, read_customers, write_discounts, read_discounts, write_discovery, read_discovery, write_draft_orders, read_draft_orders, write_files, read_files, write_fulfillments, read_fulfillments, write_gift_card_transactions, read_gift_card_transactions, write_gift_cards, read_gift_cards, write_inventory, read_inventory, write_legal_policies, read_legal_policies, write_locations, read_locations, write_marketing_events, read_marketing_events, write_merchant_managed_fulfillment_orders, read_merchant_managed_fulfillment_orders, write_metaobject_definitions, read_metaobject_definitions, write_metaobjects, read_metaobjects, write_online_store_navigation, read_online_store_navigation, write_online_store_pages, read_online_store_pages, write_order_edits, read_order_edits, write_orders, write_packing_slip_templates, read_packing_slip_templates, write_payment_customizations, read_payment_customizations, write_payment_terms, read_payment_terms, write_pixels, read_pixels, write_price_rules, read_price_rules, write_product_feeds, read_product_feeds, write_product_listings, read_product_listings, write_publications, read_publications, write_purchase_options, read_purchase_options, read_reports, write_reports, write_resource_feedbacks, read_resource_feedbacks, write_returns, read_returns, write_channels, read_channels, write_script_tags, read_script_tags, write_locales, read_locales, write_markets, read_markets, read_shopify_payments_accounts, read_shopify_payments_bank_accounts, write_shopify_payments_disputes, read_shopify_payments_disputes, read_shopify_payments_payouts, write_content, read_content, write_store_credit_account_transactions, read_store_credit_account_transactions, read_store_credit_accounts, write_themes, read_themes, write_third_party_fulfillment_orders, read_third_party_fulfillment_orders, write_translations, read_translations, read_all_cart_transforms, write_all_checkout_completion_target_customizations, read_all_checkout_completion_target_customizations, write_app_proxy, read_app_proxy, write_cart_transforms, read_cart_transforms, write_companies, read_companies, write_custom_fulfillment_services, read_custom_fulfillment_services, write_customer_data_erasure, read_customer_data_erasure, write_customer_merge, read_customer_merge, write_delivery_customizations, read_delivery_customizations, write_delivery_option_generators, read_delivery_option_generators, write_discounts_allocator_functions, read_discounts_allocator_functions, write_fulfillment_constraint_rules, read_fulfillment_constraint_rules, write_gates, read_gates, write_inventory_shipments, read_inventory_shipments, write_inventory_shipments_received_items, read_inventory_shipments_received_items, write_inventory_transfers, read_inventory_transfers, write_marketing_integrated_campaigns, read_marketing_integrated_campaigns, write_markets_home, read_markets_home, write_order_submission_rules, read_order_submission_rules, write_privacy_settings, read_privacy_settings, write_theme_code, write_validations, read_validations"

[auth]
redirect_urls = [
  "https://explain-treasure-inches-looked.trycloudflare.com/auth/callback",
  "https://explain-treasure-inches-looked.trycloudflare.com/auth/shopify/callback",
  "https://explain-treasure-inches-looked.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "distaxstaging.myshopify.com"
automatically_update_urls_on_dev = true
include_config_on_deploy = true
